version: '3'
services:
  keycloak:
    image: keycloak/keycloak
    ports:
      - '8080:8080'
    environment:
      - TZ=JST-9
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    volumes:
      - ./data:/opt/keycloak/data
    command:
      - start-dev
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - '8081:80'
